### ISSUE TITLE
Show the last thumbnail completely

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#1]
can we show the last thumbnail completely (the one on the rights hand side). See screenshot.
![inline_attachment_1 1](https://cloud.githubusercontent.com/assets/6735288/11169239/296f3c7e-8bb2-11e5-9ee0-e6e8fae940a2.png)

**Comment by Forket** [comment]
Fixed. Please approve

**Comment by heinvv** [comment]
Got it! Great.

**Comment by Forket** [comment]
OK. closing issue.
