### ISSUE TITLE
adding comment section (with jetpack comments)

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#10]
Small project

[20151116 Commenting.docx](https://github.com/Forket/connect2sa.co.za_01/files/37889/20151116.Commenting.docx)

**Comment by Forket** [comment]
>Commenting & add users to a project
Commenting
Can you please add comments to WP Theme posts and to the listings? Can you please use the Jetpack system for comments?
rigel/wptheme/avada/
I assume this won’t so much time, but please let us know if there are any complications or questions about the settings. 

Can you do the same for 
•	Website listing pages e.g. rigel/listing/again
•	Developer pages e.g. rigel/members/admin
•	Seller pages e.g. rigel/themesellers/seller-1/
•	Theme Developer pages e.g. rigel/themedeveloper/developer-1/

**Comment by Forket** [comment]
Could you please register at wordpress.com and give me login and pass. It's required to add comments from Jetpack.

**Comment by Forket** [comment]
http://www.connect2sa.co.za/rigel/listing/test/
For now I can see that U have review and discussion tabs. So comments have to be separate tab "comments" ?

**Comment by Forket** [comment]
For now I added jetpack under my account. Will wait for your registration
Also comments added. Here is:
http://www.connect2sa.co.za/rigel/listing/test/

BUT. Theme needs to be adopted (size, position, color etc). As I understand someone else is responsible for theme design.

**Comment by heinvv** [comment]
We'd like to add comments where it says "Conversations(216)". Is that possible? So that when you click on "Conversations", it displays all the comments. 

The design for that link is already there. What else do you need for it (design wise)?

**Comment by heinvv** [comment]
Do we still need to activate Jetpack?
I think that it has been activated already (http://www.connect2sa.co.za/rigel/wp-admin/admin.php?page=jetpack_modules).

**Comment by Forket** [comment]
It's activated under my account. So yes I need to activate it under yours. 


Sent from Mobile

Thanks and regards,
Aleksandr Sen
CEO | Expedition PM
Mobile: +48 532 292 764
Skype: aleksandr.sen
Email: alex@sen.pm
Social: LinkedIn | Google+
 
EXPEDITION.PM | KNOWLEDGEMAP.PM

**Comment by heinvv** [comment]
I have activated it under my account now

**Comment by Forket** [comment]
> We'd like to add comments where it says "Conversations(216)". Is that possible? So that when you click on "Conversations", it displays all the comments.
not correctly implemented. Previous developer just hardcoded this tabs ("Reviews", "Conversation"). So OK. I'll recode.

**Comment by heinvv** [comment]
Thank you.
Please go ahead.

Can you put a space in between title and brackets.
E.g.
Not like this: "Reviews(2)"
But like this: "Reviews (2)"

**Comment by Forket** [comment]
Done

**Comment by Forket** [comment]
Have you tested?

**Comment by heinvv** [comment]
http://www.connect2sa.co.za/rigel/wptheme/avada/: I can see conversations (0), but is it possible to add in that conversation part the possibility to add a comment as well?

We'd like to display in there the list of conversations, and the possibility to add a new comment.

**Comment by Forket** [comment]
It's because AVADA has option now allowing comments.
http://www.connect2sa.co.za/rigel/wp-admin/post.php?post=7645&action=edit
Please set "Allow comments." and everything will work.
![snapshot n001_2015-12-03_11-03-18](https://cloud.githubusercontent.com/assets/6735288/11557560/906cacc8-99ad-11e5-8856-074d34f3ac15.png)

**Comment by heinvv** [comment]
Observation:
On http://www.connect2sa.co.za/rigel/wptheme/test01/ I see 2 comment sections, and on http://www.connect2sa.co.za/rigel/wptheme/avada/ I see 0 comment sections. Why is that?

About http://www.connect2sa.co.za/rigel/members/admin/, http://www.connect2sa.co.za/rigel/themesellers/seller-1/ and http://www.connect2sa.co.za/rigel/themedeveloper/developer-1/: we have decided that we don't want to have comment sections on these pages. Can you please delete them on Seller and Developer page?

**Comment by heinvv** [comment]
I have test Avada. It works!

Can we automatically select the option "allow comments" for all new themes?

**Comment by Forket** [comment]
>Can we automatically select the option "allow comments" for all new themes?

It's already set

**Comment by Forket** [comment]
It was off because just someone off it for testing and have not ON it back
