### ISSUE TITLE
Slider resolution

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#11]
My second question is about meta slider. i add there a high resolution image for homepage
but it shows it like a low resolution pic

**Comment by Forket** [comment]
About quality. True is that your original image is too small (604x280) which slider tries to resize to 1080x501. Because if this you loose quality.
Advice is: make original size of image of 1080x501 px.

**Comment by heinvv** [comment]
Please don't worry about this. We are not planning on using the 1080x501 format.

**Comment by heinvv** [comment]
Great
