### ISSUE TITLE
delete listing form (advanced)

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#13]
Can you please work on these issues is in this order
1. Assigning users to projects
2. Advanced ratings
3. Delete listing request
[20151130 delete listing form.docx](https://github.com/Forket/connect2sa.co.za_01/files/47037/20151130.delete.listing.form.docx)

**Comment by Forket** [comment]
>Number of developers = 0
>Don’t show “Developers” field. 

done

**Comment by Forket** [comment]
>Adding developers

I'll create separate issue for this part in order to structure functionality. Under this issue I'll do delete listing functionality

**Comment by Forket** [comment]
#19

**Comment by Forket** [comment]
http://youtu.be/jcUUQgMsig8

**Comment by Forket** [comment]
Video test

**Comment by heinvv** [comment]
"Number of developers = 0
Don’t show “Developers” field."

Where has this been done?

I just created a new listing http://www.connect2sa.co.za/rigel/listing/8050/.

**Comment by Forket** [comment]
fixed.

**Comment by Forket** [comment]
Can you check and confirm that it works?

**Comment by heinvv** [comment]
perfect

**Comment by heinvv** [comment]
one question though: I submitted the form, but I didn't receive the email.
What email address will this form be sent to?

**Comment by Forket** [comment]
Forgot to delete my email (used for debug)
Now fixed. Please check again. 
Thanks. 


Sent from mobile

Thanks and regards,
Aleksandr Sen
CEO | Expedition PM
Mobile: +48 532 292 764
Skype: aleksandr.sen
Email: alex@sen.pm
Social: LinkedIn | Google+
 
EXPEDITION.PM | KNOWLEDGEMAP.PM

**Comment by heinvv** [comment]
The delete listing button should only be visible/enabled, when a listing has been added by admin. Not when it has been added by other users.

-----Original Message-----

**Comment by Forket** [comment]
Fixed. Done

**Comment by heinvv** [comment]
That is correct!

**Comment by heinvv** [comment]
Different question (sorry, I couldn't login onto the github page)

I tried to edit one of my own listings on
http://www.connect2sa.co.za/rigel/members/vv60/listings/my-listings/active/,
but I got an error message.

Can you please check that?
