### ISSUE TITLE
Fixing reviews

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#14]
There seems to be a problem with reviewing websites.

Every website should have their unique review section (e.g. website A get
3,4 and 3 stars, website B 2 and 5 star rating etc).

Right now I get the impression that the review section is the same for all
websites.

Please see the bottom section. Both have the same reviews displayed.
http://www.connect2sa.co.za/rigel/listing/myyyyytestttttt/
http://www.connect2sa.co.za/rigel/listing/listings-four/

**Comment by Forket** [comment]
Fixed. Now in every listing has it's own reviews.
Please check and confirm.

P.S.: I have a LOT of f******k words for person who developed reviews. :))) 8 hours for finding 1 bug. while finding i again can tell you that there will be a lot of errors in future if you will not plan your site re-coding.

**Comment by heinvv** [comment]
Thanks for fixing this.

Can you please fix it for WP Themes as well?

**Comment by Forket** [comment]
you should check

**Comment by Forket** [comment]
Have U checked?
