### ISSUE TITLE
Redirect on new listing creation if not admin

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#15]
I have just tried to create a new listing for a new user (vv60).
It didn't create the new listing. Not sure why.
And it took me to a wrong page (404 error).
Can you test the process of new listing creation as well?

**Comment by Forket** [comment]
I've found the bug in code. As I understand someone hardcoded this redirect.
This string means that if there is error on adding listing than redirect to
`members/admin/listings/add-listing/ `. 
![snapshot n001_2015-12-03_14-13-46](https://cloud.githubusercontent.com/assets/6735288/11561522/506c723c-99c8-11e5-8f3c-af6976ecf1a2.png)

**Comment by heinvv** [comment]
Cool.

Can you please fix it?

**Comment by Forket** [comment]
In the process of fixing. almost finished.

**Comment by Forket** [comment]
Fixed. Here is [video test] (http://youtu.be/KDRPNV6G5os)

**Comment by Forket** [comment]
wait few moment to view video. it's in process of uploading
