### ISSUE TITLE
ADD DEVELOPER TO THIS LISTING (Button)

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#19]
Besides the DELETE WEBSITE LISTING button, please also add this button:
ADD DEVELOPER TO THIS LISTING
When someone clicks on this button, show the following message: 
Add developer to website listing
You can add yourself as a developer to this listing, by clicking on the Add your website link, and submit that form. 

Back end logic of adding a developer
When a developer wants to add him/herself as a developer of a website he/she must submit the normal Add listing form, even if the website has been listed on our website already. 
NOTE: this only applies for developers!
In case a website has been listed on our website website listings with 0, go through all normal steps for adding a website, and just add the new developer to the list of developers. 
Must we take new screenshots: this isn’t necessary, but it won’t be a problem to take new screenshots. Please make sure that these screenshot replace the old screenshots.

**Comment by Forket** [comment]
>NOTE: this only applies for developers!

How U recognize developers in list of all users?

**Comment by Forket** [comment]
>In case a website has been listed on our website website listings 

Search BY URL,  if site already in our database?

**Comment by Forket** [comment]
I mean how to check if site already exists? by URL?

**Comment by heinvv** [comment]
Yes, I think so 

-----Original Message-----

**Comment by Forket** [comment]
http://www.connect2sa.co.za/rigel/listing/again/
could U check if it's what U wanted.

**Comment by Forket** [comment]
There is button

**Comment by heinvv** [comment]
I'll analyze more properly on Monday.

But i think that we said to only display that button, when there are no developers. Once a developer has been added to the project, this button can disappear.

-----Original Message-----

**Comment by Forket** [comment]
Got it. Will fix now. 


Sent from Mobile

Thanks and regards,
Aleksandr Sen
CEO | Expedition PM
Mobile: +48 532 292 764
Skype: aleksandr.sen
Email: alex@sen.pm
Social: LinkedIn | Google+
 
EXPEDITION.PM | KNOWLEDGEMAP.PM

**Comment by Forket** [comment]
Done.

**Comment by Forket** [comment]
could U test this issue? is it closed?

**Comment by heinvv** [comment]
Yes, it seems to be working fine
 

-----Original Message-----
