### ISSUE TITLE
"add listing" form from frontend

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#2]
In other words, update this form: http://prj.sen.pm/connect2sa.co.za/rigel/wp-admin/...
Source: "add listing" form from frontend. 

Two notes: 
1. 
You can use this form as example: http://prj.sen.pm/connect2sa.co.za/rigel/wp-admin/... 
2. 
I think we can work with custom types. Can you please try that?
3. 
The add listing script (on frontend) should have two scripts for moderation and verification. We don't need these scripts on the backend version. Only thing what we need is the script for taking screenshots and frameadding. 
4. 
The add listing script (frontend) need to be linked to screenshot + frameadding scripts as well.

**Comment by Forket** [comment]
Duplicate of #5 issue

**Comment by heinvv** [comment]
Correct!
