### ISSUE TITLE
Fix Signing up Procedure

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#20]
Please find my query in the document attached
[Adding website and Signing Up.docx](https://github.com/Forket/connect2sa.co.za_01/files/53858/Adding.website.and.Signing.Up.docx)

**Comment by Forket** [comment]
OK

**Comment by Forket** [comment]
Fixed.
Please check and confirm.
http://www.connect2sa.co.za/rigel/add-your-website/

**Comment by heinvv** [comment]
Perfect.
