### ISSUE TITLE
autosuggest tags in add listing for at frondend

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#23]
[20151207 changes to add listing form.docx](https://github.com/Forket/connect2sa.co.za_01/files/53964/20151207.changes.to.add.listing.form.docx)

**Comment by Forket** [comment]
>Autosuggest (adding themes)
Can you please create an autosuggest function for Adding Themes? When we start typing a theme name, it should automatically look for options with that content. 

Done

**Comment by Forket** [comment]
>Content of website
This works with tags, but right now this field doesn’t work properly. Can you please improve the functionality of this textbox (so that users can easily add tags)?
 Done

**Comment by Forket** [comment]
>Describe the project
Can you please make this textbox much larger?

Done

**Comment by heinvv** [comment]
Great
