### ISSUE TITLE
Add email layout and template

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#26]
This works already. The only problem is that the email doesn’t contain any layout yet. And we aren’t able to add information to this email.

**Comment by heinvv** [comment]
Why can't we change the layout and content of this email?

**Comment by Forket** [comment]
Because for now it's hardcoded and uses default WP template.
Question, are U sure that U want to have interface for managing/changing this template? BEcause:
1. I don't think that you will change it every week
2. making interface costs more than for example, if i'll use template from some file in the server, which you can change any time.

For example, attached is template which I use in my site. It's just HTML file which contains variables. And easy to manage. You can create such template at ANY html editor and just upload to the server. and it will be used by mailing system.

**Comment by Forket** [comment]
can't attach HTML. I'll send it to U at freelancer chat

**Comment by heinvv** [comment]
Thank you.

That is a perfect solution!

**Comment by Forket** [comment]
[20151207.layout.of.emails.docx](https://github.com/Forket/connect2sa.co.za_01/files/55578/20151207.layout.of.emails.docx)

**Comment by Forket** [comment]
So. Done. Little description in order to know how solution works.
- just for you to know here is how wordpress sends email and how developers send email from code: `wp_mail('alex@sen.pm','Subject','Hello Alex');`
- in folder `wp-content/plugins/Extended Functionality/html-templates/` there is file named `mail_default.html`. This is DEFAULT template for ALL emails which will be sent from your site. So this is just my example. You can prepare ANY html template you want. 
- template can contain variables (listed below) which will be replaced by corresponding values. **<message>** is required variable (this is main content of email). So available variables are:
1. **<message>**  = massage of email. In my example it will be replaced by "Hello Alex"
2. **<subject>** = will be replaced by email subject. if U plan to use subject in email template.
3. **<blogname>** = will be replaced by name of the blog taken from WordPress settings.

Below are some screenshots which demonstrate solution work

This is part of html template. As U can see it's pure html and css which ANY designer can do.
![snapshot n001_2015-12-10_21-44-38](https://cloud.githubusercontent.com/assets/6735288/11727947/44a56a98-9f87-11e5-9862-7b09104fae98.png)


This is how email is sending from code
![snapshot n001_2015-12-10_21-46-11](https://cloud.githubusercontent.com/assets/6735288/11727962/60c428b8-9f87-11e5-9f8e-fc51898f5c84.png)

This is received email in my inbox
![snapshot n001_2015-12-10_21-47-02](https://cloud.githubusercontent.com/assets/6735288/11727986/81477680-9f87-11e5-884a-6b33cce233f7.png)


Please take a look and confirm.
In order to test real email you can for example request listing deletion. System will send email to you.

**Comment by Forket** [comment]
In fact this is best solution in order not to waste a lot of money for creating some UI interface for managing template which you in fact will change once in 2 years :)

**Comment by heinvv** [comment]
Great, Alex.

I like it.

I am going to ask my designer to create a template.

**Comment by Forket** [comment]
OK. Than I close this issue as done.
You can reopen it in case of something.
