### ISSUE TITLE
fixing the logic in showing listings related to user profile

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#27]
o	Problem: right now the username is created, and user is “added” to project, but when we go to user profile, the listing doesn’t show up. 
o	E.g. I have created: http://www.connect2sa.co.za/rigel/listing/safs/
o	I have added test91@topgauge.co.za as a new user. 
o	But when I got to that profile, I don’t see this listing: http://www.connect2sa.co.za/rigel/members/test91topgauge-co-za/listings/all/

**Comment by Forket** [comment]
Fixed.
Please, check
http://www.connect2sa.co.za/rigel/members/test91topgauge-co-za/listings/all/

**Comment by heinvv** [comment]
Great.

And does the new user also get a notification email about this?
And can you approve or disapprove this?

**Comment by Forket** [comment]
>And does the new user also get a notification email about this?
And can you approve or disapprove this?

As far as I remember this is under issue #28  (notification when you assign user to listing and it's approval)
So current issue considered to be done.

**Comment by heinvv** [comment]
I don't see any listings here http://www.connect2sa.co.za/rigel/members/vv60/listings/all/, while I see listings on the vv60 user profile.

-----Original Message-----

**Comment by Forket** [comment]
it's because this user is not added to any listings
for example i've added this user as "Create Mind" in listing: 
http://www.connect2sa.co.za/rigel/wp-admin/post.php?post=8115&action=edit
![snapshot n001_2015-12-18_23-24-16](https://cloud.githubusercontent.com/assets/6735288/11908670/828d526e-a5de-11e5-838c-a7cc0dc06ee4.png)

And now U can see that this listing is in user profile.
![snapshot n001_2015-12-18_23-25-01](https://cloud.githubusercontent.com/assets/6735288/11908676/98c2e440-a5de-11e5-8e05-b15f8f463061.png)
