### ISSUE TITLE
Added with email address (complication)

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#28]
What do we do in case Rachel is a user on our platform already, but the webmaster used a different email address to invite her? 
I suggest the following: 
•	The email invitation contains a link to add herself to a listing. E.g. …/rigel/addtolisting&{listing_id}
•	When you go to that page, check if the user has been logged in or not already. 
o	If not logged in yet, pop us is shown with login / registration form
o	Please use same procedure as used for the “Add a Review” popup on this page: http://www.connect2sa.co.za/rigel/listing/again/.
•	Use the user id from the user that is logged in for the listing. Not the email address that was used in the invitation email. 
o	E.g. rachel@nerd.com is an existing user, but she got the invitation through info@nerd.com. Then she goes to …/rigel/addtolisting&{listing_id}, and uses her existing username linked to her rachel@nerd.com. Then her listing is added to that user account.

**Comment by Forket** [comment]
Done.
Please test and approve

**Comment by Forket** [comment]
For information.
With this approach when U add some person to listing (even if it's not exists) - system will not create new user. I think U understand why (you will have hundreds of "dead users" if adding to listing will not be validated by secondary person)

**Comment by Forket** [comment]
Please test not earlier than in 1 hour

**Comment by heinvv** [comment]
Fabulous!

-----Original Message-----

**Comment by Forket** [comment]
Just checked again. Works. I also like it :)
OK. Closing issue. If something - please re-open.

**Comment by heinvv** [comment]
Brilliant

-----Original Message-----
