### ISSUE TITLE
Listings and credits

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#29]
When a developer is assigned to a project (both the person who used the add listing form as invited people), then:
•	this listing should be added to their profile (http://www.connect2sa.co.za/rigel/members/admin/listings/all/).
•	A credit should be withdrawn/used from their credit list. E.g. Rachel 3 credits left, and now she has been added to a new listing. New credit balance: 2 credits. 
•	When insufficient credits, automatically show credit buying option.

**Comment by Forket** [comment]
Lets imagine situation when I add new person as developer of listing (ex. ALEX) and system in this case will create new user. Based on you requirements system should withdraw also credit from ALEX.
BUT it's a new user and because of this he has 0 credits. There is nothing to withdraw :)

**Comment by heinvv** [comment]
I disagree. But it depends how the system works exactly.

The first 5 listings are for free.

Therefore there shouldn't be a problem.

Can this work?

Afterwards: I think we should send other developers that invitation email.
They then can approve of the want to be listed on that website listing or
not.
When designer e.g. adds 6th project, the system will automatically ask
him/her to buy credit first.

**Comment by Forket** [comment]
Uh. Sorry. I forgot that user have 5 free listings. 
Ok. Working. 
Thanks. 


Sent from Mobile

Thanks and regards,
Aleksandr Sen
CEO | Expedition PM
Mobile: +48 532 292 764
Skype: aleksandr.sen
Email: alex@sen.pm
Social: LinkedIn | Google+
 
EXPEDITION.PM | KNOWLEDGEMAP.PM

**Comment by Forket** [comment]
Done.
