### ISSUE TITLE
Edit email templates from backend.

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#30]
What we need on back end side
There are a few things that I can think about.
We need to be able to set the style (head, from, subject, header, content, footer) for the two emails:
1.	Invitation as user / adding as user. >> This email does exist already. I am not sure if it is a standard Wordpress email or BuddyPress email. But I am not sure if we can change the layout of that email already. This is okay. But we’d like to improve layout. 
2.	Invitation to “join” a listing on our website. Still to be done

**Comment by Forket** [comment]
So layout for emails is covered by issue #26 .
Under this issue I'll give you possibility to edit text of message which will be used for mentioned purposes. OK?

**Comment by heinvv** [comment]
okay

**Comment by Forket** [comment]
solution ready.
take a look at `wp-content/plugins/Extended Functionality/html-templates/` folder.
Email LAYOUT file with relates to issue #26 is named `mail_default.html` as I wrote before.
Now about messages templates. For now solution is ready and tested on mail which is sent in ADD TO LISTING event (it's when U or visitor adds some person to listing developers/designers). all MESSAGE templates files starts with `message_` prefix. So in mentioned folder there is file `message_add_to_listing.html`. You can change this text as U want. This file accepts variable `<validation_url>` which responsible for URL for validation. 
So as for next steps, you can make a list of events when system should send emails. And I will develop it.
So, please check and approve current issue.

**Comment by heinvv** [comment]
Thank you 

-----Original Message-----
