### ISSUE TITLE
Moderation & verification of new website listings

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#32]
Please find some explanation in the word document attached
[20151223 Moderation.docx](https://github.com/Forket/connect2sa.co.za_01/files/70869/20151223.Moderation.docx)

**Comment by Forket** [comment]
Moderation 
URL: http://www.connect2sa.co.za/rigel/wp-admin/edit.php?post_type=directory_listing&page=moderation
Autocheck?
Can you please check if the system does this autocheck?

When User_A indicates he/she has used Theme_A, 
then the moderation script should to the website, 
and look for “wp-content/themes/{theme_A_slug}”

If: “wp-content/themes/{theme_A_slug}” is found, then automatically approve. 
Else: manual moderation needed. 

Change theme
We’d like to add one feature to this page: changing the theme. 
E.g. User_A submit a website and indicates that the theme he has used is “theme_A”, but while we moderate the theme, we find out it is “theme_B”. There should be an option to change the theme in this case. 
Emails to developers?
Do we need to inform developers about our theme moderation process? 
Our idea is NO, that isn’t necessary. As long as their websites are added and they receive an email about that (after moderation), then that is enough.

**Comment by Forket** [comment]
With moderation - it's clear for me.
About VERIFICATION (with API key). As far as I remember you decided to remove this functionality. Right?

**Comment by heinvv** [comment]
Correct. No verification with api key.

-----Original Message-----

**Comment by Forket** [comment]
>Moderation 

Done

**Comment by Forket** [comment]
>Change theme

IN process

**Comment by Forket** [comment]
>Change theme

Done

**Comment by Forket** [comment]
>Emails to developers

Changed and rewrote  code to use template.
So for now user just receives email when listing moderation status changes.
If listing is approved from start (if used theme already in the system) than user doesn't receive email (it's not needed because if his listing had theme which is already at the system)

So, please check.
