### ISSUE TITLE
"delete website" form. Client side validation.

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#34]
I tried to send a "delete website" message, and I filled in all fields, except of  phone number, and it said failed, because I hadn't filled in all fields.
Can you please check that?
Can you please change it to check fields before form has been sent?

**Comment by Forket** [comment]
Please, check.

**Comment by heinvv** [comment]
Cool.

I'll try to check it later today.

Update about verification: we have decided not to implement webmaster key validation (for now at least; we might change it later on).

Therefore the adding a website procedure is slightly easier now: 
- add website form
- moderation process
- add listing





-----Original Message-----

**Comment by heinvv** [comment]
I'll try to have a look at everything later today.

I am on holiday though. I wont have so much time.

I hope you'll be able to continue working on this.

Most important work still to do
Update moderation
Update rating and review process
Proper pagination
Update layout

Can you please give us an estimate how long this will take?

We'd like to finish all this work around January 10. Is that possible?



-----Original Message-----
