### ISSUE TITLE
Layout update: Theme profile

### ISSUE THREAD

**Issue by Forket** [Forket/connect2sa.co.za_01#37]
Based on issue #17 

Layout: http://www.connect2sa.co.za/rigel/test/profile/theme_profile.php
Implement on: e.g. http://www.connect2sa.co.za/rigel/wptheme/avada/

**Comment by Forket** [comment]
About wptheme.
But wptheme don't have slider with screenshots. Whay should I show instead?

**Comment by heinvv** [comment]
?

I thought you had creates a slider for wpthemes (e.g. Avada) as well. Have you never done that?

Can you please create a slider for that as well?

-----Original Message-----

**Comment by Forket** [comment]
it's done :) I temporary switched it off :) and forgot about this :))))

**Comment by Forket** [comment]
Hello
So for today will finish this issue.
http://www.connect2sa.co.za/rigel/wptheme/avada/
I've rewrote 100% of code in this template, because there was real mess. So now everything optimized and is alike your design template.
Small things left and will report you in the evening.

**Comment by Forket** [comment]
Where in this your example button "Add review" ?
http://www.connect2sa.co.za/rigel/test/profile/theme_profile.php#

**Comment by heinvv** [comment]
It seems we have forgotten that.

Can you pleae add that button in the right top corner of the review panel
(where it shows the number of shares and comments)?

[image: Inline images 1]

**Comment by Forket** [comment]
Done. Could you please check wptheme layout?

**Comment by heinvv** [comment]
Thank you, Alex.

I just came back from holidays.

I'll send you feedback tomorrow.

**Comment by heinvv** [comment]
What do you suggest for "write review" button?
Did you see my comment about that?

**Comment by Forket** [comment]
Agreed. Because while making design i'm optimizing your site and code.
For example on this layout:
1. there were 450 queries to DB - now it's 160
2. On one page there were 8 loops in order to show content. now it's 1 loop.
3. there were more than 1300 lines of UNSTRUCTURED code - now it's about 200 with good structure which will understand every developer.

Writing it to you just to inform, because you remember when I wrote to you that you have very buggy solution.

**Comment by Forket** [comment]
About review button - i've added it.
Clicking it - opens popup window for adding review. it's form from previous developer which is also not correct:
1. Mistakes in code
2. no structure
3. no template for modification.
4. uses not protected ajax requests ( in this case your site can be compromised)
5. Uses pop-up approach. If you wanna have responsive design you shouldn't use popups in your design.

Of course it's up to you to decide. If you want, I can recode it.

**Comment by heinvv** [comment]
:)

Thanks, Alex!

**Comment by heinvv** [comment]
Questions:
Review button: where have you added it?

"no template for modification." I don't think we want modification (yet).

"uses not protected ajax requests": that is serious.

"Uses pop-up approach" If I am not mistaken these popups work perfectly on
smartphone. I have checked it. What do you say about that? Have you checked
it? Or what do you suggest?

How long would it take you to rewrite this?

**Comment by Forket** [comment]
>Review button: where have you added it?
![snapshot n001_2016-01-13_13-43-38](https://cloud.githubusercontent.com/assets/6735288/12294560/c1bfaa28-b9fb-11e5-8ee4-f73877ff00b6.png)

It only shows if you HAVE NOT provided review yet. If you already provided - I don't show this button.

>"no template for modification." I don't think we want modification (yet).
Modification - it's not from point of your view. I mean, for example, wpthemes and listings have reviews section (and it's even the same design) and in old solution there were separate code for this - but should be one place for such sections. In development it's named "templating code". And with this approach it has more performance and usability.

>"uses not protected ajax requests": that is serious.

At least wpnonce should be used to protect ajax calls.

>"Uses pop-up approach" If I am not mistaken these popups work perfectly on
smartphone. I have checked it. What do you say about that? Have you checked
it? Or what do you suggest?

![snapshot n001_2016-01-13_13-49-54](https://cloud.githubusercontent.com/assets/6735288/12294687/98ac9ec4-b9fc-11e5-8c9a-845a48ff0e58.png)

This is how review form visible from iPhone: mess in fields and labels, black frame which uses useful space etc. My opinion, 
1. rewrite in order not ti use popups (even in desktop version it's not a good tone nowadays to use popups for visitor)
2. When desktop layout will be finished - make mobile optimization.

**Comment by heinvv** [comment]
Can you please rewrite it?

But my question: What technique would you use instead? What is the alternative?

-----Original Message-----

**Comment by Forket** [comment]
1. Yes, I can. Ok
2. I suggest when user clicks button than form for adding review slides down (with java animation) and user can complete this form. On completion it slides out and system message " Thanks for review" 
:) it's best approach.

**Comment by heinvv** [comment]
Yes, please.

Can you please create the Ajax form?

-----Original Message-----
