### ISSUE TITLE
improve image quality

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#4]
First question: is there really an issue with image quality?
Or is imagequality reduced once used inside slider?

**Comment by Forket** [comment]
> is there really an issue with image quality?

this case I plan to investigate

**Comment by Forket** [comment]
>is imagequality reduced once used inside slider?

It's for sure NOt because of slider. Slider plugin doesn't do any manipulations with image. Most of all it uses actual size (which is sized with imagemagic).

**Comment by heinvv** [comment]
Something is going wrong with slider page. 
Please see attachment
[Please compare.docx](https://github.com/Forket/connect2sa.co.za_01/files/35372/Please.compare.docx)

**Comment by heinvv** [comment]
![image](https://cloud.githubusercontent.com/assets/11960838/11179839/e8c352ca-8c5e-11e5-87f4-3b607cdaa8f6.png)

**Comment by heinvv** [comment]
Can you please get back to me about this?
This is my most urgent point. 
Because I think possibly we can leave everything else how it is, once we can fix this. 

The images are better than visible inside the slider.

**Comment by heinvv** [comment]
I think I know what the problem is. 

The pictures are save with a width like 1089 pixels. 
But we should save them with width of 726 pixels.

**Comment by heinvv** [comment]
Can you please analyse what image size they should be?

**Comment by heinvv** [comment]
I am checking it now.

**Comment by heinvv** [comment]
Sorry, I am getting confused. 
I guess it might have to with resizing because of screen size. 
I check, and realised that your image is 726 pixels.

**Comment by Forket** [comment]
In attachment i've saved 2 images. one from slider, another from uploads folder. it's two sources taken from your DOC.
1. As U can see they even have EQUAL file size: 125 KB (128 281 bytes)
2. I can assume that in your DOC example this could be additional factor because you used some tool to take screenshot from images.

OK. going forward. few moments, i'll compare one more thing.

**Comment by heinvv** [comment]
Can you otherwise send me a screenshot how you see the slider?
For me it is a huge difference. 
But maybe not on different pc with different screen size

I use chrome

**Comment by heinvv** [comment]
This is how I see the page
![image](https://cloud.githubusercontent.com/assets/11960838/11182343/c2a96016-8c72-11e5-8b75-99d8f216c533.png)

The slider seems to be much wider than it should be, because the lines stop much earlier already. Or is this cause by something else?

**Comment by heinvv** [comment]
Comparison of two pages (screenshots cut in photoshop): 
http://prj.sen.pm/connect2sa.co.za/rigel/wptheme/studio/
http://themes.themegoods2.com/rigel/demo/skyscraper-near-empire-state-building-wins-backing/?rigelstyle=15 (original theme file)


![image](https://cloud.githubusercontent.com/assets/11960838/11182645/e6c74b32-8c74-11e5-981f-aff66abe39cb.png)

**Comment by heinvv** [comment]
http://prj.sen.pm/connect2sa.co.za/rigel/wptheme/studio/
![image](https://cloud.githubusercontent.com/assets/11960838/11182655/fd1835b8-8c74-11e5-80c0-f4451291b6bd.png)

**Comment by heinvv** [comment]
http://themes.themegoods2.com/rigel/demo/skyscraper-near-empire-state-building-wins-backing/?rigelstyle=15
![image](https://cloud.githubusercontent.com/assets/11960838/11182661/04259c74-8c75-11e5-8300-f67afc949d85.png)

**Comment by Forket** [comment]
So i've removed following CSS and quality changed. Please check.
``` image-rendering:optimizeSpeed;             /* Legal fallback */
    image-rendering:-moz-crisp-edges;          /* Firefox        */
    image-rendering:-o-crisp-edges;            /* Opera          */
    image-rendering:-webkit-optimize-contrast; /* Safari         */
    image-rendering:optimize-contrast;         /* CSS3 Proposed  */
    image-rendering:crisp-edges;               /* CSS4 Proposed  */
    image-rendering:pixelated;                 /* CSS4 Proposed  */
    -ms-interpolation-mode:nearest-neighbor;   /* IE8+           */
```

**Comment by Forket** [comment]
check in 2 mins

**Comment by heinvv** [comment]
Great!

**Comment by heinvv** [comment]
Up to the next task!
Thank you.

**Comment by Forket** [comment]
Deal. Moving forward 


Sent from Mobile

Thanks and regards,
Aleksandr Sen
CEO | Expedition PM
Mobile: +48 532 292 764
Skype: aleksandr.sen
Email: alex@sen.pm
Social: LinkedIn | Google+
 
EXPEDITION.PM | KNOWLEDGEMAP.PM
