### ISSUE TITLE
Theme seller page

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#44]
http://www.connect2sa.co.za/rigel/themesellers/seller-1/

The layout of the buttons has changed

I am not sure if the rating section is working. The number of reviews is incorrect. It says 145 reviews, but that is incorrect. I think it should be 1 review.

**Comment by heinvv** [comment]
Same issues on this page: http://www.connect2sa.co.za/rigel/themedeveloper/developer-1/

**Comment by Forket** [comment]
Themeseller and the,e developers pages and layout i've not completed yet.
Will plan and do.

**Comment by Forket** [comment]
Issue #49  and #50
