### ISSUE TITLE
create back end form for adding website

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#5]
create back end form for adding website

**Comment by Forket** [comment]
1. Is there any description of requirements for this form?
2. Is there any graphic vision of this form? it can be just simple image where I can see position and amount of elements of this form.

**Comment by heinvv** [comment]
This form exist on front end side already. 
We simply want to be able to create a listing from back end side (wp-admin) as well. 
Same requirements/fields as front end form. 
Graphic: standard wordpress. 
Please use "add theme", "add theme seller" etc as example.

**Comment by heinvv** [comment]
Correct

**Comment by Forket** [comment]
So. [this is](http://www.connect2sa.co.za/rigel/members/admin/listings/add-listing/?) front-end form for adding listing. and you want alike form to be in back-end instead if [this](http://www.connect2sa.co.za/rigel/wp-admin/post-new.php?post_type=directory_listing). Am I right?

**Comment by heinvv** [comment]
About forms: these are the correct links indeed.

**Comment by Forket** [comment]
OK. i''ve designed image prototype: how form should look like from backend site. Please take a look and confirm or give your comments.
![snapshot n001_2015-11-16_17-55-23](https://cloud.githubusercontent.com/assets/6735288/11188667/4d5738b4-8c8c-11e5-8376-6b4bcd4c8d07.png)

**Comment by heinvv** [comment]
Looks great!
Please go ahead

-----Original Message-----

**Comment by heinvv** [comment]
By when do you think you'll be able to finish this page?

**Comment by heinvv** [comment]
Hi Alex, 

We hope that you'll be able to finish this page today. 

We really would like to make progress with this project. 

We'd like to ask you a huge favour: can you please indicate per day if you'll be working for us the next day? We have been waiting for your updates for the whole day, but we didn't see anything. 

It is a bit tough for us when things are so unpredictable. At least as we know when to expect what, then it is a bit easier for us.

**Comment by Forket** [comment]
Hello. I'll try to make release today.
Also question, can I reach U by phone? tell me your number, i'll call.

**Comment by heinvv** [comment]
Sorry, I am out tonight. Can't really call now.

-----Original Message-----

**Comment by Forket** [comment]
Have question. 
In this add listing form (in front-end) there are fields:
*Website url
*Website url of content page 1
*Website url of content page 2
*Describe the project
*Project description
* etc...

Where these fields are stored? in fact those developer who created this form - should know it.
I need this information in order to store information in correct place.

**Comment by heinvv** [comment]
Custom fields?

Is that answer helpful?

Can't you seen in the script where it is saved?

-----Original Message-----

**Comment by Forket** [comment]
I understand that it's custom fields. But I need to know form logic.
Because as I can see from front-end that when you add new listing  - submit action creates listing AND website entry.
BUT there could be some other logic which I don't see. Only form developer knows :))

**Comment by Forket** [comment]
Because in fact I have form. Take a look:
http://prj.sen.pm/connect2sa.co.za/rigel/wp-admin/post-new.php?post_type=directory_listing

Screenshot:
![snapshot n001_2015-11-17_20-28-00](https://cloud.githubusercontent.com/assets/6735288/11222262/cdd7dec0-8d69-11e5-8c27-7137bc418b86.png)

**Comment by heinvv** [comment]
I guess Listing creation is enough.

Not sure what you mean by website entry.

There could be a check for theme and webmaster verification check, but we don't need those fun too on the backend side.

Is this helpful?

-----Original Message-----

**Comment by Forket** [comment]
OK. in this case form is ready.
about fields. ALL of the fields from FRONT-end must be in BACK-end?

**Comment by heinvv** [comment]
Yes, I think so.

-----Original Message-----

**Comment by heinvv** [comment]
About http://prj.sen.pm/connect2sa.co.za/rigel/wp-admin/post-new.php?post_type=directory_listing: great work. 

One question: can you please activate screenshot functionality to this form as well?

About working faster: yes, please! My phone number is +27763717454.

**Comment by heinvv** [comment]
I really hope that we can improve the speed of this project. I had expected that you would have been able to finish both backend form and credits by Monday already.

Right now we feel that we are just waiting all the time. That is frustrating for us.

Otherwise we'd rather look for a developer who has more time.

-----Original Message-----

**Comment by heinvv** [comment]
Yes, we want these fields.
I suggest the following (for back end):

Developer Type; Username

You can delete "Select Developer" and Email (Optional). Instead create textboxes for username (of designer; programmer etc)

**Comment by Forket** [comment]
Ok. This is faster. Will do it today after training. 
Don't worry. From Monday I will utilize all my time for your project. 


Sent from Mobile

Thanks and regards,
Aleksandr Sen
CEO | Expedition PM
Mobile: +48 532 292 764
Skype: aleksandr.sen
Email: alex@sen.pm
Social: LinkedIn | Google+
 
EXPEDITION.PM | KNOWLEDGEMAP.PM

**Comment by heinvv** [comment]
Great!

**Comment by Forket** [comment]
Published changes. Please check and approve

**Comment by Forket** [comment]
Here is example: http://prj.sen.pm/connect2sa.co.za/rigel/wp-admin/post.php?post=8151&action=edit

**Comment by heinvv** [comment]
Hi Alex,

Thank you so much for your work.

I am not inside the office now. I'll try to get back to you in a couple of
hours.

Can you please work in this order:
- 5 monthly credits
- advanced ratings
- assigning developer to website listings

**Comment by heinvv** [comment]
Feedback for Alex:

1) Outdated version: we have updated a few things on the connect2sa.co.za
version of the website. We are sorry about that. There have been a few
developers who have updated items on the website, but they all have
finished their work, or are finishing up their work. From now on you will
be the only developer working on the website. Please find instructions how
to deal with updates below.

2) Update fixing:
If I am not mistaken, you have worked so far on four pages:
2.1) Theme page for image slider (on website)
2.2) Website listing page for image slider (on website)
2.3) Back end form of Add Listings.
2.4) Back end form a Add WP Themes

Strategy:
About 2.1+2: please leave image slider on your host for now. We'll ask you
at a later stage to implement your changes. We still need to update the
layout of these pages on connect2sa.co.za version.

About 2.3: For back end form of Add Listings: can you please carefully
study the updates that have been made to that script (especially front end;
possibly backend), and then implement your changes on the connect2sa.co.za
host?
Or, in other words, please don't just upload your version, but add the
changes that you have made to the version of the page that is available on
connect2sa.co.za.

About 2.4: Please leave this page for now, but there is one developer
finishing off some work. He might want to make some changes to that page.
I'll ask you to implement your changes, once he has finished all his work
(1 or 2 days left).

3) Comments on back end form:
- Please add fields for content pages 1 and 2
- Please add website content field (with tags)
- Please add AUTOCOMPLETION to  "Theme of website"
- Please delete project description.

4) We are not so happy about the AUTOCOMPLETION that is available on
http://www.connect2sa.co.za/rigel/members/admin/listings/add-listing/?: can
you please try to improve that functionality?

**Comment by heinvv** [comment]
Please let us know when there are serious problems with this for you.

Can you please also have a look at the log file from one of the developers?

See file attached.

**Comment by heinvv** [comment]
Please also study this new page:
http://www.connect2sa.co.za/rigel/wp-admin/edit.php?post_type=directory_listing&page=moderation

Explanation: Add Listing script (front end) checks for two things: 
1) If user has added his/her verification key (like the Google webmaster verification key) to the HEAD of the webpage. If not, then user can't add that webpage. This to prevent that people add websites that aren't their own work to the website. 
2) Check if website uses the theme indicated by user in Add Listing form. If not, then this listing is added to moderation page. We then will check what theme is used. 

We don't want these features for the back end form. We want, as administrators, to be able to add any website that we want to. 
Therefore, please no verification and moderation add to back end form.

**Comment by heinvv** [comment]
Sorry for the hassle right now, but I am sure we'll be able to get past this. 
From now on you'll be the only developer working on this website.

**Comment by Forket** [comment]
>Back end form a Add WP Themes

I haven't worked with this form. your task was to make " Add Listings" form

**Comment by Forket** [comment]
> we have updated a few things on the connect2sa.co.za

I need to know what was updated in order to take a look if I used it in my solution. For example, custom fields name etc. are they the same?

**Comment by heinvv** [comment]
Oh, I see.

I thought you might have used that form to create screenshot creation of
themes. But I guess you have used chronjobs only?

**Comment by heinvv** [comment]
Can you please study that?

**Comment by Forket** [comment]
>please leave image slider on your host for now. We'll ask you
at a later stage to implement your changes.

slider and forms and at the same plugin. And in order to split it - I have to recode my solution. This issue is because at the start you asked me to develop slider and I didn't know about further plans (planning issue we talked about)

**Comment by heinvv** [comment]
Sorry for this confusion.

But after this you are the only person working here.

**Comment by heinvv** [comment]
Sorry again about the confusion.

But it might be easier because you have use a plugin.

I guess in that case can you just upload the plugin? Is that possible?

**Comment by Forket** [comment]
>But I guess you have used chronjobs only?
I don't' use cron job (we just talked about it). Screenshot is taken in the process of creation listing (there is also delay when you submit form.

**Comment by Forket** [comment]
>I guess in that case can you just upload the plugin? Is that possible?

Of course. I will upload plugin and there will be slider, screenshots and form functionality.

**Comment by heinvv** [comment]
Brilliant

**Comment by Forket** [comment]
I suggest you that when project/site will be completed you should initiate project to refactor the code and increase it's performance and usability. For example:
1. make screenshots with cronjob
2. Combine plugins 
3. clear the code and add comments to functions etc.
4. general and SEO optimization (use DB cache, minification, CDN, compression, clear headers, use webp images instead of png,  etc)

**Comment by heinvv** [comment]
Thank you for your suggestions.
I like that.

**Comment by Forket** [comment]
Solution transfered to your env.
As I understand - this ticked closed. Please, open new issue if there will be some bugs.
