### ISSUE TITLE
5 monthly free credits

### ISSUE THREAD

**Issue by heinvv** [Forket/connect2sa.co.za_01#6]
Create 5 monthly free credits

Sources: 
http://prj.sen.pm/connect2sa.co.za/rigel/wp-admin/edit.php?post_type=directory_listing&page=directory_settings
http://prj.sen.pm/connect2sa.co.za/rigel/wp-admin/admin.php?page=directory_settings&tab=payments

In this system we can charge users/subscribers for their listings. 
Right now we have set 1 listing for 1 credit. 
We'd like to add a function to this. 
We'd like to give all first 5 listings/credits for free. 
Every subscriber can add 5 listings for free, and these listings continue to be free. These subscribers shouldn't be charged. 

Once you have more than 5 listings, now you'll be charged. 

What about the "5 free credits when you sign up"? Answer: these credits are valid for one month only. With these credits we can create listings for the first month only. 

I am not sure how to develop/programm this. Can you please make a suggestion?

Two ideas: 
1. 
Only start counting credits once the number of listings is larger than 5. 
2. 
Give 5 free credits every month. 
Problem with this: if people have less than 5 listings, then they can start "saving credits". I don't think that that will work. We don't want that.

**Comment by Forket** [comment]
in your solution you use plugin named "Directory" http://premium.wpmudev.org/project/wordpress-directory

Question: is this your plugin (you/your company is the owner) OR you just downloaded this plugin to use in your project?

**Comment by heinvv** [comment]
We have bought this plugin from wpmudev

-----Original Message-----

**Comment by Forket** [comment]
OK. Than.
1. I will extend this plugin and it means that if you in future will update it - my customization will be overwritten. And because of this please be very carefull and in case of update please ask me or other developer to perform code comparison.
2. So what if your final vision about credits? for example, i'm as user registered 1th on December and for 30th of Dec i've added 4 listings. What system should do at 1st of Jan? - options:
  - hide "add listing" button.
  - Tell the user to buy more credits. 
 - etc

**Comment by Forket** [comment]
>I am not sure how to develop/programm this. Can you please make a suggestion?

Start charging when one of 2 conditions is true:
1. User reached 5 listings
2. 1 month passed from the user registration date.
In this scenario you will be protected from "saving credits" and users have ability to use 5 listings during 1st month from registration

**Comment by heinvv** [comment]
1. We'll switch updates for this plugin off
2. Please use standard procedure. It gives message about buying more credits. You can leave that part as it is.
Please try to create new user, and to create new listings. Then you'll see.
Right now we might have given users 5 free credits. Please change that to zero in admin, and see what happens for new users.

3. From now on, please make changes straight on connect2sa server.

-----Original Message-----

**Comment by heinvv** [comment]
First option. Once reached 5 listings.

Users pay upfront.



-----Original Message-----

**Comment by heinvv** [comment]
I have set the number of Signup Credits to 0. 
That is easier for testing as well. 

When you create a new user, and you want to create a listing for that user, you should be asked automatically to buy more credits. 

See 
![image](https://cloud.githubusercontent.com/assets/11960838/11392455/8c449918-9362-11e5-85a7-2e4cb6f97844.png) (from this page: http://www.connect2sa.co.za/rigel/wp-admin/admin.php?page=directory_settings&tab=payments)

**Comment by heinvv** [comment]
When you create a new user, and you'd like to Add a website (front end), then you get this message: 
![image](https://cloud.githubusercontent.com/assets/11960838/11393524/c672cb40-9368-11e5-82b7-b2b61343e5a6.png)

Url: http://www.connect2sa.co.za/rigel/listings/signup/

**Comment by heinvv** [comment]
When you'd like to add a new listing, you need to verify that you are the webmaster of this website. 
I have installed a webmaster verification tool on connect2sa.co.za/rigel/

You can always use the rigel website. 
You only need to change the specific line: 
![image](https://cloud.githubusercontent.com/assets/11960838/11397475/6675f59a-9382-11e5-9dd9-ad08c8020de4.png)
http://www.connect2sa.co.za/rigel/wp-admin/tools.php?page=wp-site-verification-tool_manage

**Comment by Forket** [comment]
>When you create a new user, and you'd like to Add a website (front end), then you get this message: 

From even current functionality when user reaches credit limit he will be asked for payment. BUT for now I can see TWO places for adding listing. Here is [FIRST] ( http://prj.sen.pm/connect2sa.co.za/rigel/members/admin/listings/add-listing/) form and here is [SECOND] (http://prj.sen.pm/connect2sa.co.za/rigel/create-listing/). when I use FIRST link yes system asks me to buy credits (i've set 0 in settings) and when I use SECOND system allows me to create listing. Most of all in SECOND link there is different form for adding lising. SO: where is the correct link and which one will be used in production version?
![snapshot n001_2015-11-25_20-58-32](https://cloud.githubusercontent.com/assets/6735288/11408116/723ca9de-93b7-11e5-8b81-2fe1d85bc2c7.png)

3.

**Comment by heinvv** [comment]
We only first form.
Can you please delete second form?

-----Original Message-----

**Comment by Forket** [comment]
![snapshot n001_2015-11-26_20-30-20](https://cloud.githubusercontent.com/assets/6735288/11429731/8f12d5cc-947c-11e5-8ea4-4feace87c8a1.png)
 want to ask about this setting. By default (default plugin behaviour), this 5 credits (if user have not used it) will expire in one month? have you tested it?

**Comment by heinvv** [comment]
I don't know if it expires. I don't think so.
But this setting is very different.

When a new user registers, he/she receives a certain number of credits once off.

E.g. 5 credits received.
And when user has 3 listings.
Then first month is for free.
After one month 2 credits left (5 minus 3).
User needs to buy credits at beginning of 2nd month.


-----Original Message-----

**Comment by heinvv** [comment]
Hi Alex,

I hope everything is going well.

Can you please update me on the progress?

**Comment by Forket** [comment]
Done. Please make a test already in your env.

**Comment by heinvv** [comment]
I am going to test tomorrow

**Comment by Forket** [comment]
OK. As I understand issue closed. If you will have bugs in future, please open new issue.
Moving to the next open questions.

**Comment by heinvv** [comment]
I have just tried to create a new listing for a new user (vv60). 

It didn't create the new listing. Not sure why. 

And it took me to a wrong page (404 error). 

Can you test the process of new listing creation as well?

![image](https://cloud.githubusercontent.com/assets/11960838/11473928/f03cdc22-977d-11e5-82be-63068020a037.png)

**Comment by heinvv** [comment]
For some reason it takes me to .../members/ADMIN/listings, while I am logged in as VV60 (see right top corner)

**Comment by Forket** [comment]
Got it. Will take a look. 


Sent from Mobile

Thanks and regards,
Aleksandr Sen
CEO | Expedition PM
Mobile: +48 532 292 764
Skype: aleksandr.sen
Email: alex@sen.pm
Social: LinkedIn | Google+
 
EXPEDITION.PM | KNOWLEDGEMAP.PM

**Comment by Forket** [comment]
this behaviour is not under my solution. Because I don't manage adding listings. My solution just WAITS for adding listing in order to do my staff. Most of all, my plugin now switched off. 
As result I can tell that you have some bug in functionality.

**Comment by heinvv** [comment]
Can you please help us out here?

Plugin has always worked

Probably something with adding script goes wrong 

-----Original Message-----

**Comment by Forket** [comment]
>Can you please help us out here?

I'll open issue with this #15
